version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "[dependabot] "
      include: "scope"

